server {

    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;

    index index.html;

    # redirect root → register
    location = / {
        return 302 /index;
    }

    # remove .html from URL
    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    # redirect *.html → without .html
    location ~ ^(.+)\.html$ {
        return 302 $1;
    }

}
