CREATE TABLE [dbo].[User] (
    [Id] INT IDENTITY(1,1) NOT NULL,
    [Name] NVARCHAR(255) NOT NULL,
    [Login] NVARCHAR(255) NOT NULL,
    [Password] NVARCHAR(500) NOT NULL,
    [Blocked] BIT NOT NULL DEFAULT 0,
    [Deleted] BIT NOT NULL DEFAULT 0,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT GETDATE(),
    [UpdatedAt] DATETIME2 NULL,
    CONSTRAINT [User_PK] PRIMARY KEY ([Id])
);